#!/usr/bin/env bash
# Vendor a stdlib version from lumen-effects into stdlib/<version>/ and write a
# checksum manifest.
#
#   scripts/vendor-stdlib.sh <lumen-effects-tag> [version]
#
# Nothing is fetched at build time. The copy lives in this repo so builds are
# hermetic and work offline — which an embedded toolchain needs — and so that
# compilation is deterministic: the same source plus the same stdlib version
# plus the same compiler produces byte-identical bytecode. That is what makes a
# signed program reproducible by an auditor.
#
# The cost is that a stdlib release needs a lumen-core release to reach users.
# Accepted, because stdlib versions are additive and old ones never disappear.
#
# RE-VENDORING AN EXISTING VERSION IS ALMOST ALWAYS WRONG. An effect declaring
# `stdlib 1` must compile to the same bytecode in two years as it does today,
# and that is only true if v1 never changes. Additions go into a new version.
# The script refuses unless --force is given.

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
effects="${LUMEN_EFFECTS:-$root/../lumen-effects}"

force=0
worktree=0
args=()
for a in "$@"; do
  case "$a" in
    --force) force=1 ;;
    # Before the first lumen-effects release there is no tag to vendor from.
    # This copies the working tree instead and records that plainly in the
    # manifest, rather than naming a tag that does not exist.
    --from-worktree) worktree=1 ;;
    *) args+=("$a") ;;
  esac
done

if [ "$worktree" -eq 1 ]; then
  tag="UNRELEASED-worktree"
  version="${args[0]:-v1}"
elif [ "${#args[@]}" -lt 1 ]; then
  echo "usage: $0 <lumen-effects-tag> [version] [--force]" >&2
  echo "       $0 --from-worktree [version] [--force]" >&2
  exit 2
else
  tag="${args[0]}"
  version="${args[1]:-v1}"
fi
dest="$root/stdlib/$version"

if [ ! -d "$effects/.git" ]; then
  echo "no lumen-effects checkout at $effects" >&2
  echo "clone the siblings with lumen-dev/scripts/clone-all.sh, or set LUMEN_EFFECTS" >&2
  exit 1
fi

if [ -f "$dest/manifest.toml" ] && [ "$force" -eq 0 ]; then
  echo "$version is already vendored." >&2
  echo "" >&2
  echo "Re-vendoring an existing version changes the bytecode every effect that" >&2
  echo "declares it compiles to, which breaks the reproducibility the vendoring" >&2
  echo "exists to provide. Add stdlib/v<N+1>/ instead." >&2
  echo "" >&2
  echo "If you are certain (an unreleased version, say), pass --force." >&2
  exit 1
fi

echo "vendoring $version from lumen-effects ($tag)"
if [ "$worktree" -eq 1 ]; then
  files=$(cd "$effects/stdlib/$version" 2>/dev/null && ls *.lfx 2>/dev/null || true)
else
  src_ref="$tag:stdlib/$version"
  files=$(git -C "$effects" ls-tree --name-only "$src_ref" 2>/dev/null || true)
fi
if [ -z "$files" ]; then
  echo "no stdlib/$version to vendor from $tag" >&2
  exit 1
fi

mkdir -p "$dest"
manifest="$dest/manifest.toml"
{
  echo "# Generated by scripts/vendor-stdlib.sh. Do not edit."
  echo "#"
  echo "# These files are copies. Change them in lumen-effects and re-vendor;"
  echo "# editing them here makes these checksums lie."
  echo ""
  echo "source = \"lumen-effects\""
  echo "tag = \"$tag\""
  echo "version = \"$version\""
  echo ""
} > "$manifest"

for f in $files; do
  case "$f" in
    *.lfx) ;;
    *) continue ;;
  esac
  if [ "$worktree" -eq 1 ]; then
    cp "$effects/stdlib/$version/$f" "$dest/$f"
  else
    git -C "$effects" show "$src_ref/$f" > "$dest/$f"
  fi
  sum=$(sha256sum "$dest/$f" | cut -d' ' -f1)
  {
    echo "[[file]]"
    echo "name = \"$f\""
    echo "sha256 = \"$sum\""
    echo ""
  } >> "$manifest"
  echo "  $f  $sum"
done

echo ""
echo "Vendored into $dest"
echo "Now add the version to VERSIONS in crates/lumen-lang/src/stdlib.rs if it is new,"
echo "and run: cargo test -p lumen-lang"
